apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: {{ .Release.Name }}
            image: busybox:1.36.0-glibc
            imagePullPolicy: IfNotPresent
            command:
              - 'env'
            envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cm

