---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - 'env'
      #- sleep
      #- "86400" 
    envFrom:
    - configMapRef:
        name: {{ .Release.Name }}-cm
  restartPolicy: Never
